#PUERTO
server:
  port: 4000

#EUREKA
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

#GATEWAY
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          #lower-case-service-id: true
      routes:
      - id: user
        uri: lb://user
        predicates:
        - Path=/user/**
        filters:
        - AuthFilter
      - id: product
        uri: lb://product
        predicates:
        - Path=/product/**
      - id: cart
        uri: lb://cart
        predicates:
        - Path=/cart/**
      - id: auth
        uri: lb://auth
        predicates:
        - Path=/auth/**
        filters:
        - Request