server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: user
        uri: lb://user
        predicates:
        - Path=/users/**
      - id: product
        uri: lb://product
        predicates:
        - Path=/products/**
      - id: cart
        uri: lb://cart
        predicates:
        - Path=/carts/**