#PUERTO ${PORT:${SERVER_PORT:0}}
server:
  port: ${PORT:${SERVER_PORT:0}}

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

# ZIPKIN
spring:
  application:
    zipkin:  ${ZIPKIN_SERVER_ADDRESS:http://localhost:9411}
management:
  tracing:
    sampling:
      probability: 1